jobs:
  central-sync:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: v${{ github.event.inputs.release_version }}
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      env:
        GPG_FILE: ${{ secrets.GPG_FILE }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD
          }}
        GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME
          }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      name: Publish to Sonatype OSSRH
      run: 'echo $GPG_FILE | base64 -d > secring.gpg

        ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

        '
name: Maven Central Sync
on:
  repository_dispatch:
    types: trigger-ga___central-sync.yml
