jobs:
  build:
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD
        }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME
        }}
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    needs: build_matrix
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: pre-build
      name: Pre-Build Steps
      uses: micronaut-projects/github-actions/graalvm/pre-build@master
      with:
        distribution: graalvm
        java: ${{ matrix.java }}
    - continue-on-error: true
      env:
        GH_TOKEN_PUBLIC_REPOS_READONLY: ${{ secrets.GH_TOKEN_PUBLIC_REPOS_READONLY
          }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GRAALVM_QUICK_BUILD: true
      id: build
      name: Build Steps
      uses: micronaut-projects/github-actions/graalvm/build@master
      with:
        nativeTestTask: ${{ matrix.native_test_task }}
    - continue-on-error: true
      id: post-build
      name: Post-Build Steps
      uses: micronaut-projects/github-actions/graalvm/post-build@master
      with:
        java: ${{ matrix.java }}
    strategy:
      matrix:
        java:
        - '17'
        - '21'
        native_test_task: ${{ fromJson(needs.build_matrix.outputs.matrix).native_test_task
          }}
      max-parallel: 6
  build_matrix:
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD
        }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME
        }}
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: build-matrix
      name: Build Matrix
      uses: micronaut-projects/github-actions/graalvm/build-matrix@master
name: GraalVM Latest CI
on:
  repository_dispatch:
    types: trigger-ga___graalvm-latest.yml
