jobs:
  build:
    env:
      GH_TOKEN_PUBLIC_REPOS_READONLY: ${{ secrets.GH_TOKEN_PUBLIC_REPOS_READONLY }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD
        }}
      GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME
        }}
      PREDICTIVE_TEST_SELECTION: ${{ github.event_name == 'pull_request' && 'true'
        || 'false' }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      TESTCONTAINERS_RYUK_DISABLED: true
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: "\U0001F5D1 Free disk space"
      run: 'sudo rm -rf "/usr/local/share/boost"

        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

        sudo apt-get clean

        df -h

        '
    - continue-on-error: true
      name: "\U0001F4E5 Checkout repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: "\U0001F527 Setup GraalVM CE"
      uses: graalvm/setup-graalvm@v1.2.1
      with:
        distribution: graalvm
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: "\U0001F527 Setup Gradle"
      uses: gradle/gradle-build-action@v3.3.2
    - continue-on-error: true
      name: "\u2753 Optional setup step"
      run: '[ -f ./setup.sh ] && ./setup.sh || [ ! -f ./setup.sh ]

        '
    - continue-on-error: true
      id: gradle
      name: "\U0001F6E0 Build with Gradle"
      run: './gradlew check --no-daemon --continue

        '
    - continue-on-error: true
      if: env.SONAR_TOKEN != '' && matrix.java == '17'
      name: "\U0001F50E Run static analysis"
      run: './gradlew sonar

        '
    - continue-on-error: true
      if: always()
      name: "\U0001F4CA Publish Test Report"
      uses: mikepenz/action-junit-report@v4
      with:
        check_name: Java CI / Test Report (${{ matrix.java }})
        check_retries: 'true'
        report_paths: '**/build/test-results/test/TEST-*.xml'
    - continue-on-error: true
      if: matrix.java == '17'
      name: "\U0001F4DC Upload binary compatibility check results"
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
      with:
        name: binary-compatibility-reports
        path: '**/build/reports/binary-compatibility-*.html'
    - continue-on-error: true
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      if: success() && github.event_name == 'push' && matrix.java == '17'
      name: "\U0001F4E6 Publish to Sonatype Snapshots"
      run: ./gradlew publishToSonatype docs --no-daemon
    - continue-on-error: true
      id: docs_target
      name: "\u2753 Determine docs target repository"
      uses: haya14busa/action-cond@v1
      with:
        cond: ${{ github.repository == 'micronaut-projects/micronaut-core' }}
        if_false: ${{ github.repository }}
        if_true: micronaut-projects/micronaut-docs
    - continue-on-error: true
      env:
        BRANCH: gh-pages
        FOLDER: build/docs
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        TARGET_REPOSITORY: ${{ steps.docs_target.outputs.value }}
      if: success() && github.event_name == 'push' && matrix.java == '17'
      name: "\U0001F4D1 Publish to Github Pages"
      uses: micronaut-projects/github-pages-deploy-action@master
    strategy:
      matrix:
        java:
        - '17'
        - '21'
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
